name = "cinema-worker"
main = "worker/src/index.ts"
compatibility_date = "2025-12-01"

[vars]
UPSTREAM_BASE = "https://cinesphere.com.vn"
GMAIL_SENDER_EMAIL = "no-reply@cinesphere.com.vn"
GMAIL_SENDER_NAME = "CTBOOKING"
VITE_SERVER_BASE_URL = "https://cinesphere.com.vn"
VITE_VNPAY_RETURN_URL = "/checkout"
VITE_VNPAY_GATEWAY = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VITE_MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"

[[d1_databases]]
binding = "cinema_db"
database_name = "cinema-db"
database_id = "9bae4fb3-570a-4ded-9a75-922ce4d6ef81"
