name = "cinema-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
send_metrics = false
workers_dev = true
preview_urls = true

[vars]

VITE_SERVER_BASE_URL = "https://cinesphere.com.vn"
VITE_CLIENT_BASE_URL = "https://cinesphere.com.vn"
VITE_VNPAY_RETURN_URL = "/checkout"
VITE_VNPAY_GATEWAY = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VITE_MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"
VITE_MOMO_REDIRECT_URL = "/checkout"
VITE_MOMO_IPN_URL = "/api/momo/ipn"
R2_PUBLIC_BASE = "https://cinesphere.com.vn"
R2_PUBLIC_ENABLED = "false"
GMAIL_SENDER_EMAIL = "no-reply@cinesphere.com.vn"
GMAIL_SENDER_NAME = "CINESPHERE"
BREVO_SENDER_EMAIL = "no-reply@cinesphere.com.vn"
BREVO_SENDER_NAME = "CINESPHERE"
VITE_RATE_LIMIT_BOOKING_CHECK_MAX = "10"
VITE_RATE_LIMIT_BOOKING_CHECK_WINDOWMS = "60000"

[[d1_databases]]
binding = "cinema_db"
database_name = "cinema-db"
database_id = "9bae4fb3-570a-4ded-9a75-922ce4d6ef81"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "e2a5a9184efb40afb73b7a17a41c9328"

[ai]
binding = "AI"

[env.preview]

[env.preview.placement]
mode = "smart"

[env.preview.vars]
IS_PREVIEW = "true"

VITE_SERVER_BASE_URL = "https://cinema-worker-preview.baonhat20.workers.dev"
VITE_CLIENT_BASE_URL = "https://preview.cinema-pages.pages.dev"

VITE_MOMO_REDIRECT_URL = "/checkout"
VITE_MOMO_IPN_URL = "/api/momo/ipn"
VITE_VNPAY_RETURN_URL = "/checkout"
VITE_VNPAY_GATEWAY = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"

VITE_MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"
R2_PUBLIC_BASE = "https://preview.cinema-pages.pages.dev"
R2_PUBLIC_ENABLED = "false"
GMAIL_SENDER_EMAIL = "no-reply@cinesphere.com.vn"
GMAIL_SENDER_NAME = "CINESPHERE"
BREVO_SENDER_EMAIL = "no-reply@cinesphere.com.vn"
BREVO_SENDER_NAME = "CINESPHERE"
VITE_RATE_LIMIT_BOOKING_CHECK_MAX = "10"
VITE_RATE_LIMIT_BOOKING_CHECK_WINDOWMS = "60000"
VITE_CLOUDINARY_CLOUD_NAME = "dzp3rbeix"
VITE_CLOUDINARY_UPLOAD_PRESET_VIDEO="ctbooking_videos_unsigned"
VITE_CLOUDINARY_UPLOAD_PRESET_IMAGE="ctbooking_images_unsigned"


[[env.preview.d1_databases]]
binding = "cinema_db"
database_name = "cinema-db-preview"
database_id = "fd9274ae-d1a3-42e2-b83d-2fc1bdc71caf"

[[env.preview.kv_namespaces]]
binding = "KV_BINDING"
id = "e2a5a9184efb40afb73b7a17a41c9328"

[env.preview.ai]
binding = "AI"

[env.production]
routes = [
  { pattern = "cinesphere.com.vn/api/*", zone_name = "cinesphere.com.vn" },
  { pattern = "cinesphere.com.vn/uploads/*", zone_name = "cinesphere.com.vn" },
  { pattern = "cinephere.com.vn/api/*", zone_name = "cinephere.com.vn" },
  { pattern = "cinephere.com.vn/uploads/*", zone_name = "cinephere.com.vn" }
]
[observability]
enabled = false
head_sampling_rate = 1
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = false
